version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: master
    assignees:
      - oanhnn
    reviewers:
      - oanhnn
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: Asia/Ho_Chi_Minh
    labels:
      - dependencies

  - package-ecosystem: docker
    directory: /
    target-branch: master
    assignees:
      - oanhnn
    reviewers:
      - oanhnn
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: Asia/Ho_Chi_Minh
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: /
    target-branch: master
    assignees:
      - oanhnn
    reviewers:
      - oanhnn
    schedule:
      interval: weekly
      day: monday
      time: "12:00"
      timezone: Asia/Ho_Chi_Minh
    labels:
      - dependencies
