name: Test

on:
  # Build the nightly version at at 8:20 AM UTC
  schedule:
    - cron: "20 8 * * *"

  # For all pushes to the main branch run the tests and push the image to the
  # GitHub Container Registry under an edge tag
  push:
    branches:
      - master
      - develop

  # For all PRs to the develop branch run the tests
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node:
          - 18
          - 19
          - 20
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setting up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run tests
        run: pnpm run test
